name: download
on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Create a File
      run: echo "hello from" > file_1.txt
    - uses: actions/upload-artifact@v4
      with:
        name: |
         ##[add-mask]bacon
         %0Atest
        path: .
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact-1
        path: .
  download:
    needs: upload
    runs-on: ubuntu-latest
    env:
      FLAG: ${{ secrets.FLAG }}
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v5
      # with:
        # path: my-artifact
        # pattern: my-artifa*
        # merge-multiple: true
    - run: ls -R .
