name: e2e

on:
  deployment_status:

jobs:
  a:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        uses: something/interesting@main
        with:
          FLAG: ${{ secrets.FLAG }}
          URL: ${{ github.event.deployment_status.environment_url }}
