name: issue comment
on:
  issue_comment:

jobs:
    process:
        runs-on: ubuntu-latest
        env:
            APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
            COMMENT: ${{ github.event.comment.body }}
        steps:
            - run: echo "$COMMENT"
            - run: echo "nothing"
