name: issue comment
on:
  issue_comment:

jobs:
    process:
        runs-on: ubuntu-latest
        env:
            APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
        steps:
            - uses: raven-actions/debug@v1.2.0
