name: input
on:
  workflow_dispatch:
    inputs:
      a:
        
jobs:
  a:
    runs-on: ubuntu-latest
    env:
      a: ${{ github.event.inputs.a }}
    steps:
      - run: echo $a
      - run: echo ${{ secrets.FLAG }} > test.txt
