name: input
on:
  workflow_dispatch:
    inputs:
      a:
        
jobs:
  a:
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.FLAG }}
    steps:
      - run: echo ${{ github.event.inputs.a }}
