name: issue comment
on:
  issue_comment:

jobs:
    process:
        runs-on: ubuntu-latest
        env:
            DOUBLE_FLAG: ${{ secrets.DOUBLE_FLAG }}
        steps:
            - run: echo "TEST"
