name: issue comment
on:
  issue_comment:

jobs:
    process:
        runs-on: ubuntu-latest
        env:
            PAT: ${{ secrets.PAT }}
            COMMENT: ${{ github.event.issue_comment.body }}
        steps:
            - run: echo "$COMMENT"
            - run: echo "nothing"
