name: input
on:
  workflow_dispatch:
    inputs:
      a:
        
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: QuebecBashing/bashit/.github/actions/test@main
        with:
          token: ${{ secrets.FLAG }}
          something: ${{ github.event.inputs.a }}
