name: input
on:
  workflow_dispatch:

jobs:
    process:
        runs-on: ubuntu-latest
        env:
            # DOUBLE_FLAG: ${{ secrets.DOUBLE_FLAG }}
            PREFIX: prefix
            TEST: test
            SUFFIX: suffix
        steps:
            - run: |
                NEW_TEST="test%0A  SUFFIX: suffix"
                echo "$NEW_TEST"
                echo "::add-mask::$NEW_TEST"
            - run: echo ""

