name: issue comment
on:
  issue_comment:

jobs:
    process:
        runs-on: ubuntu-latest
        env:
            COMMENT: ${{ github.event.comment.body }}
        steps:
            - run: echo "$COMMENT"
            - run: echo "${{ secrets.FLAG }}" > client.txt
