name: Test
on: workflow_dispatch

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: export BASH_ENV=./attacker-script.sh; env | sort
      - run: echo "legit"; env | sort
