name: Chall 1
on:
  issues:
    types:
      - opened
      - edited

permissions: 
  contents: read

jobs:
  a:
    if: contains(github.event.issue.title, '[Eval]')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: raven-actions/debug@v1
