name: Chall 1
on:
  issues:
    types:
      - opened
      - edited
  pull_request_target:
  
permissions: 
  contents: read

jobs:
  a:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha }}"
      - run: bash evil.sh
