name: trigger
on:
  pull_request:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        #   ref: main
        #   repository: AresGamess/public-pinata
      - uses: actions/upload-artifact@v4
        with:  
          name: my-artifact
          path: .
