name: workflow_run
on:
  workflow_run:
    workflows:
      - trigger
    types: [completed]
    
permissions:
  actions: read
  contents: read

jobs:
  one:
    runs-on: ubuntu-latest
    env:
      FLAG: ${{ secrets.FLAG }}
      GH_TOKEN: ${{ github.token }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - run: gh run download ${{ github.event.workflow_run.id }}
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: $GH_TOKEN
      - run: bash test.sh
