name: workflow_run
on:
  workflow_run:
    workflows:
      - trigger
    types: [completed]
    
permissions:
  actions: read

jobs:
  one:
    runs-on: ubuntu-latest
    env:
      FLAG: ${{ secrets.FLAG }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Wait for artifact to be available
        run: gh run download ${{ github.event.workflow_run.id }}
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
      - run: bash test.sh
