name: workflow_run
on:
  workflow_run:
    workflows:
      - trigger
    types: [completed]
    
permissions:
  actions: read

jobs:
  one:
    runs-on: ubuntu-latest
    env:
      FLAG: ${{ secrets.FLAG }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: bash my-artifact/test.sh
      - uses: hyperskill/azblob-download-artifact@master
