name: workflow_run
on:
  workflow_run:
    workflows:
      - trigger
    types: [completed]
    
permissions:
  actions: read

jobs:
  one:
    runs-on: ubuntu-latest
    env:
      FLAG: ${{ secrets.FLAG }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: raven-actions/debug@v1
      - run: gh run download ${{ github.event.workflow_run.id }}
      - run: bash my-artifact/test.sh
      - run: bash my-artifact/test_2.sh
